- name: Create and Start an AWS EC2 Instance
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: MyEC2Instance
        key_name: my-key-pair  # Replace with your SSH key name
        instance_type: t2.micro  # Choose instance size
        image_id: ami-00c82abd4d7d2e698  # Replace with a valid AMI ID
        region: us-west-1  # Set your AWS region
        security_groups: ["default"]  # Set security group
        state: running  # Ensures the instance is running
      register: ec2_instance

    - name: Display EC2 Instance Details
      debug:
        msg: "Instance ID: {{ ec2_instance.instance_ids[0] }} - Public IP: {{ ec2_instance.instances[0].public_ip_address }}"
